titlle: Tejas Vilas Patil
logo: "profile..jpeg?raw=ture"
desciption: >
QA Tester
<br><br>
<a href="mailto:Tejasvp87@gmail.com">Tejasvp87@gmail.com </a>
      <br>
      <a href="https://www.linkedin.com/in/tejas-patil-0087//">LinkedIn Profile</a>
      <br>
theme: jekyll-theme-minimal
