<header>
   <h1><a href="https://tejasp87.github.io/Tejas_Patil/">Tejas Vilas Patil</a></h1>
   <img src="/profile.jpeg?raw=true" alt="Logo">
   <p>QA tester
      <br><br>
      <a href="mailto:Tejasvp87@gmail.com">Tejasvp87@gmail.com </a>
      <br>
      <a href="https://www.linkedin.com/in/tejas-patil-0087//">LinkedIn Profile</a>
   </p>
   <p class="view"><a href="https://github.com/aashimaahuja">View My GitHub Profile</a></p>
</header>
<footer>
   <p><small>Hosted on GitHub Pages — Theme by <a href="https://github.com/orderedlist">orderedlist</a></small></p>
</footer>
<br>

theme: jekyll-theme-tactile