titlle: Tejas Vilas Patil #name
logo: "profile.jpeg?raw=ture" #logo
desciption: > #line
 <h1> QA Tester </h1> 
    <br><br>
    <a href="mailto:Tejasvp87@gmail.com"> Tejasvp87@gmail.com </a>
    <br>
    <a href="https://www.linkedin.com/in/tejas-patil-0087//"> LinkedIn Profile </a>
    <br>
theme: jekyll-theme-minimal
